# syntax=docker/dockerfile:1

FROM node:18-alpine

WORKDIR /app

COPY ["package.json", "package-lock.json*", "tailwind.config.js", "./"]
COPY src /app/src
COPY public /app/public

RUN npm install 

CMD ["npm", "start"]
